name: hyperpay
description: A new Flutter plugin project.
version: 0.0.1

environment:
  sdk: ">=2.19.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.nyartech.hyperpay
        pluginClass: HyperpayPlugin
      ios:
        pluginClass: HyperpayPlugin